### ISSUE TITLE
Polymer 3

### ISSUE THREAD

**Issue by joeblew99** [Polymer/prpl-server-node#46]
Will this be needed with Polymer 3 ?

Am a bit confused, because i presume that with polymer 3 we can just build with webpack for es5 and es6.

**Comment by krumware** [comment]
This is not a required tool. Emphasis here is demonstrating a method of serving specific builds to clients with specific capabilities.

More questions can be asked at polymer.slack.com

**Comment by tycho01** [comment]
The [3.0 preview post](https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview) mentioned PRPL for 3.0 as being WIP. Is there an issue we can follow on that? I saw none over there, just this one over here.

**Comment by aomarks** [comment]
Hi @tycho01, there shouldn't be any differences on the serving side for a Polymer 3.0 project vs 2.0, at least that I can think of so far. A Polymer 3.0 project should look very similar to a 2.0 one from the server's perspective, except that components will be served primarily from `.js` files instead of `.html` files.

The recommended practices for building a Polymer 3.0 project is still a WIP, though (i.e. whether and how `polymer build` will support bundling Polymer 3.0 projects). I'm not aware of an issue for that discussion on GitHub; you might like to file a new issue at https://github.com/Polymer/polymer-build to start it!
