### ISSUE TITLE
Picking a fallback preset

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/prpl-server-node#51]
If I only deploy one preset, `es6-bundled` for example, and try to load the site on IE11, I don't get a broken site, I get a 500 error. To me that's a bit weird: what if I don't actually _have_ any es6 in that es6 bundle? What if it's really late in the site, and I haven't clicked on the page that runs it. I'd vote that using any of the bundles as a fallback (or the closest to es5) would be better in this case, but I mostly wanted to get a conversation started and see what y'all think

**Comment by aomarks** [comment]
This is documented here: https://github.com/Polymer/prpl-server-node#capabilities

My preference is to be explicit. If your bundle didn't actually require ES6 such that it could load in IE11, just remove the `es2015` tag from the build config and you'll get the behavior you described.

**Comment by notwaldorf** [comment]
Hmm, so in my `polymer.json` I just use the presets, and not the capabilities bit:
```
"builds": [
    {
      "preset": "es5-bundled",
      "basePath": true
    },
    {
      "preset": "es6-bundled",
      "basePath": true
    },
    {
      "preset": "es6-unbundled",
      "basePath": true
    }
  ]
```
Should I do that instead?

**Comment by aomarks** [comment]
Given the config above, I would expect IE11 to be served the `es5-bundled` build, because that preset has no capabilities (https://github.com/Polymer/polymer-project-config/blob/master/src/builds.ts#L155).

FYI if you did want to override the capabilities of a build with a preset, you can set the `browserCapabilities` field yourself, and it will override that part of the preset (true for any preset field actually). (I would personally prefer to just define my own build instead of using a preset, though, since otherwise the naming is kind of confusing).

**Comment by notwaldorf** [comment]
Yes, sorry, I meant If I don't have that, like if my `polymer.json` is just 
```
"builds": [
    {
      "preset": "es6-bundled",
      "basePath": true
    },
]
```
Then I would have expected `es6-bundled` to be used as a broken fallback on IE11.

**Comment by aomarks** [comment]
Ah I see, nope, the current behavior is to strictly respect the `browserCapabilities` you specify (in this case via a preset), and to return an error when you encounter a behavior where no builds could be served. If you **really** want that above build to be served to all browsers, you can add `"browserCapabilities": []`. You could also define a custom build -- that might be a bit less confusing (just because "es6" is in the name).
