### ISSUE TITLE
support polymer 3.0 imports

### ISSUE THREAD

**Issue by phil-mitchell** [Polymer/prpl-server-node#72]
Polymer 3.0 imports modules by module name instead of by path name.  Most browsers don't support that.  Can this server automatically adapt the import statements like polymer-cli does?

**Comment by aomarks** [comment]
Because prpl-server is intended to be used in production, it's important for it to do as little as possible, both for performance and security.

You're better off transforming bare module specifiers to URLs once, up front, using a tool like `polymer build`. During development you can use `polymer serve` to do the transform on the fly.

See also the response to a related question here: https://github.com/Polymer/prpl-server-node/issues/55#issuecomment-340065002
